# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java build with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
        architecture: x64  
    - name: Build and Publish
      # Yes we need to enable tests once the DB prerequisites are fixed
      run: mvn -B package deploy -DskipTests --file pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
